### ISSUE TITLE
A question in filtering out the detections for evaluation

### ISSUE THREAD

**Issue by JianxiangFENG** [dimitymiller/openset_detection#3]
Hi dear author,

thank you for sharing the codes!
I have a question regarding the filtering process of raw detections from the detector.

Specifically, what does it mean of this [line](https://github.com/dimitymiller/openset_detection/blob/68a52575e8bff2ba16b060c9965cc3e67874fd6a/mmdetection/test_data.py#L180)? `j` should be the index of detected instances in that image, which has nothing to do with the number of class, what does the comment of this line mean by saying `#winning class must be class j for this detection to be considered valid`?

Best regards,
jianxiang.

**Comment by dimitymiller** [comment]
`j` is actually a class index, and `results[j]` gives us an array of the detections for that specific class.

The 'result' variable is a list of length N, where N = #number of training classes. Each element in the list is an array with the detections belonging to a specific class. Each row in the array is a single detection, of format [bounding box, class_score, logit_distribution]. 

The typical detection pipeline creates a class detection as long as the class score is above a certain threshold (e.g. 0.2). For example, if there's a bounding box where class 'dog' has score 0.6 and class 'cat' has score 0.3, then this detection will appear twice in 'result' --> once in the 'dog' array of detections, and another time in the 'cat' array of detections. In our paper, we only want to create a detection for the class that had the greatest score (as it can't be both a cat and a dog). 

Hopefully that makes sense. You can print the result variable on line 167 if you want to see the setup of the class list of detections. 

Otherwise, let me know if there's anything else you want to ask or I'll close this issue tomorrow.

**Comment by JianxiangFENG** [comment]
Thanks for the timely and detailed reply. The format you described should come from this [function](https://github.com/dimitymiller/openset_detection/blob/68a52575e8bff2ba16b060c9965cc3e67874fd6a/mmdetection/mmdet/core/bbox/transforms.py#L99), right?

**Comment by JianxiangFENG** [comment]
> The typical detection pipeline creates a class detection as long as the class score is above a certain threshold (e.g. 0.2). For example, if there's a bounding box where class 'dog' has score 0.6 and class 'cat' has score 0.3, then this detection will appear twice in 'result' --> once in the 'dog' array of detections, and another time in the 'cat' array of detections. In our paper, we only want to create a detection for the class that had the greatest score (as it can't be both a cat and a dog).

regrading this example, I have another concern. Since the bbox prediction is class-dependent. So there won't be an exactly same bbox with `dog` of 0.6 and `cat` of 0.3. Intuitively, because they are not exactly the same (maybe with a high IoU), it could be the case that a dog overlaps with a small cat, which makes sense and would not require to just take the one with highest score. Then the way you described will exclude these cases.

**Comment by dimitymiller** [comment]
Yes, the format comes from the function you've linked -- although note that we have altered the [multiclass_nms function](https://github.com/dimitymiller/openset_detection/blob/68a52575e8bff2ba16b060c9965cc3e67874fd6a/mmdetection/mmdet/core/post_processing/bbox_nms.py#L7) so that we also return the logit distribution (not standard from mmdet).

Yes, the bounding boxes are class-dependent and won't be exactly the same. You're right that there is a potential that one proposal is capturing 2 different objects -- and thus by only allowing 1 detection per proposal, some objects may be missed. However, this is likely to be a very small number of cases and could only happen when two objects are highly overlapping. Faster R-CNN also returns 1000 object proposals, so we assume that there will be a proposal that better captures each object (e.g. proposal for the cat and another proposal for the small cat), and hopefully each proposal will get the correct corresponding classification and prevent this from happening.

Object detectors are developed for best performance with mAP metric, which rewards high recall as possible, even if this means sacrificing precision. In practice, this often means that there are many, many FP's (not suitable for robotics case). In our paper, we opt for this approach because it removes a large number of FP's, with only minimal FN's introduced.
