### ISSUE TITLE
Logit shape change in euclideanDistance()

### ISSUE THREAD

**Issue by johnsk95** [dimitymiller/openset_detection#4]
Hello, while using your code with my dataset I encountered a dimension error which traced to the line below:

https://github.com/dimitymiller/openset_detection/blob/657bbaede8b3eab78cfa8eab35bfcdd1c84fa6e2/mmdetection/mmdet/models/losses/anchor_cross_entropy_loss.py#L113

In the euclideanDistance method, the input logit is reshaped (_, num_classes+1) to account for the background class.
This creates a dimension error in anchor_cross_entropy since the first shape of ```mask``` and ```distances``` do not match.
https://github.com/dimitymiller/openset_detection/blob/657bbaede8b3eab78cfa8eab35bfcdd1c84fa6e2/mmdetection/mmdet/models/losses/anchor_cross_entropy_loss.py#L51
I'm confused if just naively reshaping the logit to fit the additional background class is correct. 
Can you please provide some reasoning behind this code?
Thank you in advance!

**Comment by dimitymiller** [comment]
The object detectors used in the paper (Faster R-CNN and RetinaNet) produce a logit for each training class (self.num_classes) and an extra logit for the background class. Other object detector architectures don't predict a logit for the 'background' class explicitly and will not produce the same dimension logit vector.

If you're only changing the dataset and not changing the architecture, a dimension error seems strange. Are you creating AnchorwCrossEntropyLoss with the num_classes your object detector was trained for (rather than the num_classes in the test dataset)? For example, a COCO-trained detector should have num_classes = 80, even if you test on a different dataset.

**Comment by johnsk95** [comment]
Thanks for the timely reply!
As you said RetinaNet is supposed to produce an additional class prediction for background. 
Turns out there's a mistake in my custom config that prevents that, which resulted in the aforementioned dimension error. 
Thank you for the clarification!
