### ISSUE TITLE
Anchor-less object detectors

### ISSUE THREAD

**Issue by ApoorvaSuresh** [dimitymiller/openset_detection#5]
Hi,
I'd like to know if this approach still would work with Anchor-less object detectors such as FCOS, VFNet, etc. since there's an Anchor loss term being used.

**Comment by dimitymiller** [comment]
This approach can be used with anchor-less object detectors. The 'Anchor' loss term does not refer to the anchors of the object detector -- instead it is talking about the idea of 'anchoring' the class-specific features at a fixed point in the logit space. Please see [our paper](https://arxiv.org/abs/2104.01328) for more details, noting that the Anchor loss term itself was actually introduced in [this paper](https://openaccess.thecvf.com/content/WACV2021/html/Miller_Class_Anchor_Clustering_A_Loss_for_Distance-Based_Open_Set_Recognition_WACV_2021_paper.html) which explored open-set classification.

Also worth noting -- we found in the paper that you can often get high performance without using the Anchor loss term but still modelling the logit space with GMMs. This requires a larger number of GMM components due to the less structured logit space.

Let me know if you have any follow up questions!
